name: Build & Test

on:
  pull_request:
    branches: [master, next]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
      - run: npm ci

      - name: Run ESLint
      - run: npm run lint

      - name: Build the lib
      - run: npm run build --if-present

      - name: Run tests
      - run: npm test:coverage
