name: On Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches: [ master, next ]

jobs:
  vulnerabilities-check:
    name: Check dependencies vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Vulnerabilities check
        uses: frontegg/workflows/.github/shared-actions/vulnerabilities-check@master
        with:
          node_version: '18'

  call-lint:
    uses: ./.github/workflows/_lint.yaml

  call-build-and-test:
    needs: call-lint
    uses: ./.github/workflows/_build-and-test.yaml

  call-pre-release:
    needs: call-build-and-test
    uses: ./.github/workflows/_pre-release.yaml