name: Publish

on:
  push:
    branches: [ master, next ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm run build

      - name: Semantic Release
        run: npx semantic-release
