name: Publish

on:
  push:
    branches: [ master, next ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.event.pusher.email }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm run build

      - name: Semantic Release
        run: npx semantic-release
